export const APP_INITIALIZE = 'APP_INITIALIZE';
export const APP_SHUTDOWN = 'APP_SHUTDOWN';
export const APP_OPEN_CONTEXT_MENU = 'APP_OPEN_CONTEXT_MENU';
export const APP_CLOSE_CONTEXT_MENU = 'APP_CLOSE_CONTEXT_MENU';
export const APP_MODAL_MESSAGE_OPEN = 'APP_MODAL_MESSAGE_OPEN';
export const APP_MODAL_MESSAGE_CLOSE = 'APP_MODAL_MESSAGE_CLOSE';
export const APP_SET_DROPDOWN_ID = 'APP_SET_DROPDOWN_ID';

export const SEARCH_SET_STRING = 'SEARCH_SET_STRING';
export const SEARCH_SET_TOKENS = 'SEARCH_SET_TOKENS';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REFRESH = 'USER_REFRESH';
export const USER_EDIT = 'USER_EDIT';
export const USER_GET_CUSTOMER = 'USER_GET_CUSTOMER';
export const USER_SET_PASSWORD = 'USER_SET_PASSWORD';
export const USER_APPLY = 'USER_APPLY';
export const USER_GET_DATA = 'USER_GET_DATA';
export const USER_PUT_DATA = 'USER_PUT_DATA';
export const USER_SEND_RESET_EMAIL = 'USER_SEND_RESET_EMAIL';
export const USER_SET_LOGIN_DATA = 'USER_SET_LOGIN_DATA';

export const ADMIN_GET_SIGNUPS = 'ADMIN_GET_SIGNUPS';
export const ADMIN_DELETE_SIGNUP = 'ADMIN_DELETE_SIGNUP';
export const ADMIN_GET_CUSTOMERS = 'ADMIN_GET_CUSTOMERS';
export const ADMIN_DELETE_USER = 'ADMIN_DELETE_USER';
export const ADMIN_ACTIVATE_SIGNUP = 'ADMIN_ACTIVATE_SIGNUP';

export const ANALYTICS_EVENT = 'ANALYTICS_EVENT';
export const ANALYTICS_PAGEVIEW = 'ANALYTICS_PAGEVIEW';
export const ANALYTICS_USER_UPDATE = 'ANALYTICS_USER_UPDATE';